### ISSUE TITLE
vscode-styled-components interferes with autocomplete in javascript

### ISSUE THREAD

**Issue by nicholasbraun** [styled-components/vscode-styled-components#136]
When I type javascript, sometimes i get weird autocompletes.

For example when I type:

```javascript
wrapper.find(
````
as soon as I type the opening bracket, it autocompletes it to:

```javascript
wrapper.BiquadFilterNode()
```

![screen shot 2018-09-21 at 11 34 58](https://user-images.githubusercontent.com/29401371/45873733-6f4d9e00-bd93-11e8-8888-2c820589a842.png)

I narrowed the cause of this behaviour down to vscode-styled-components by disabling every extension i have installed and trying out every extension alone one by one and it only happens when I have vscode-styled-components enabled.

**Comment by allevaton** [comment]
I've also noticed this and similarly have tracked it down to `vscode-styled-components`.

It can also _very_ strangely interact with Code's highlighting. See:

![2018-09-21 10_51_14-clipboard](https://user-images.githubusercontent.com/4457995/45888555-555c8d00-bd8c-11e8-8527-144390b237fa.png)

It mostly happens when formatting with Prettier with JSX, but have also seen it in TypeScript files (not TSX).

**Comment by franky47** [comment]
I had similar issues, see #132, which has been escalated to an issue in Microsoft/typescript-styled-plugin.

**Comment by vilic** [comment]
Same here in a TypeScript project. https://github.com/Microsoft/TypeScript/issues/27233

**Comment by vilic** [comment]
Seems to be an issue with `typescript-styled-plugin`, can reproduce with the plugin configured and this extension disabled.

**Comment by deftomat** [comment]
The similar issue for me. After I added an `export` right before `interface`.

![image](https://user-images.githubusercontent.com/5549148/46737517-f78cd800-cc9b-11e8-8b48-3ca602031ada.png)

I need to add one new character to make this error disappear or I need to type `export` slowly.

Happens only when this extension is active.
