### ISSUE TITLE
latest typescript support invalid color 

### ISSUE THREAD

**Issue by aaalsubaie** [styled-components/vscode-styled-components#138]
I just updated to 
`    "styled-components": "^4.0.0-beta.9",
`

in order to use typescript props. it works like a charm but without colors! (notice the one without Props works)

![screen shot 2018-10-01 at 5 19 29 pm](https://user-images.githubusercontent.com/1550029/46294313-2ae5ad80-c59e-11e8-8dc4-c44617fd7472.png)

**Comment by osdiab** [comment]
`styled-components@4.0.2`, `@types/styled-components@4.0.1`, and it's failing in the same way for writing code [as they document it on the `styled-components` website](https://www.styled-components.com/docs/api#styling-components), for example:

<img width="564" alt="screen shot 2018-10-20 at 2 20 51 am" src="https://user-images.githubusercontent.com/1890926/47233809-cc7a5500-d40e-11e8-903b-30bc5f33efc8.png">

Aside, @aaalsubaie does that syntax actually work for you? It's throwing typescript errors for me, rather than `styled.div<{stuff...}>` don't you have to do `styled<{stuff...}, "div">("div")`?
