### ISSUE TITLE
Highlighting template literals interceptions correctly

### ISSUE THREAD

**Issue by iddan** [styled-components/vscode-styled-components#17]
Because of the extensions interceptions in the template literals used for styled components are not highlighted correctly.

```JSX
styled.div`
    background: ${({ row }) => row % 2 ? '#fff' : '#f5f5f5'};
`;
```
<img width="386" alt="screen shot 2017-03-16 at 12 15 04" src="https://cloud.githubusercontent.com/assets/12671072/23991527/525b3268-0a42-11e7-983d-c0cf7a4ecc39.png">

**Comment by Cu3PO42** [comment]
I cannot confirm any issues with interpolated expressions at this time. I presume that it would have been fixed by #49.

Since there has also not been any activity here in quite some time I am going to close this for now. If you still experience issues, please do let us know and we'll try to fix them.
