### ISSUE TITLE
0.0.27 version syntax highlighting bug with template literals

### ISSUE THREAD

**Issue by U1320100568** [styled-components/vscode-styled-components#200]
i meet the problem that there is a property named "css", and colon( : ) in template litarals

0.0.26 | 0.0.27
-------|------
![image](https://user-images.githubusercontent.com/35591116/68822806-daabab00-06cc-11ea-9df0-2627221dbb4f.png) | ![image](https://user-images.githubusercontent.com/35591116/68822768-c10a6380-06cc-11ea-85a6-fe5c1da2e945.png)

**Comment by jrmatos** [comment]
Same problem.

**Comment by jserrao** [comment]
Specifically, variables inside of template literal is where I see issues.

<img width="572" alt="Screen Shot 2019-12-11 at 1 12 07 PM" src="https://user-images.githubusercontent.com/947542/70647950-12e4d180-1c18-11ea-90ed-355383ca77b3.png">

**Comment by MosheSommers** [comment]
Having similar issue with hsl(). Seems to be happening on all css functions i.e. linear-gradient().
It seems the parentheses is confusing it.

**Comment by jasonwilliams** [comment]
I have the above issue if there's no semi-colon, but when it hit save prettier adds one and the highlighting is correct. I think the former picture is happening because you're creating a style-rule with no semi-colon and that breaks the highlighting rules, i think today most people are formatting and aren't bumping into this.

As this issue is quite old im going to close (as there's been many versions since this was raised). Feel free to raise a new issue if this is still a problem
