### ISSUE TITLE
CSS variables autocomplete

### ISSUE THREAD

**Issue by yeion7** [styled-components/vscode-styled-components#321]
Hey 👋 

Thanks for the project!

Would it be possible to add code completion for css variables defined like this?

const GlobalStyle = createGlobalStyle`
  :root {
      --border-width: 1px;
  }
`

**Comment by jasonwilliams** [comment]
Hey @yeion7 could you flesh this out a bit? Which bit from that do you want to autocomplete? Could you show where the cursor would be also?

**Comment by yeion7** [comment]
@jasonwilliams oh sorry, 

Let's say that I have 

_globalStyles.js_

```js
export const GlobalStyle = createGlobalStyle`
  root: { 
    --border-width: 1px; 
  }
` 
```

And then I creating a button component

_button.js_

```
const Button = styled.button`
  ...;
  border-width: var(...); /* I'd like to have the variable autocomplete here */
`
```

I would like to have the variable autocomplete in other files, now I only have autocomplete in _globalStyles.js_ where I defined the global variables

**Comment by jasonwilliams** [comment]
Ok I see, I doubt that is possible in our current state and I'll explain why. Or at least... I'll explain as much as I know so far (then maybe you can go from there)

The intellisense is farmed out to https://github.com/microsoft/typescript-styled-plugin (everything in-between the backticks) 
That will look at the CSS as a whole and add autocomplete etc by using data from the CSS Language Service. It will see things like `border-width:` and offer options like `thin`, `medium`, `initial` etc because thats what the [CSS Language Service](https://github.com/microsoft/vscode-css-languageservice) returns.

From what I understand, there is no state. So when a block of CSS is parsed, its not held in memory and re-used for when another block of CSS is parsed. Each block is parsed and processed in standalone.

Luckily you're not alone. There has been a feature request for the CSS Language Service to support variables across files here:
https://github.com/microsoft/vscode-css-languageservice/issues/156

If the above is supported we could potentially utilise it here (or in TS Styled Plugin), but this would need to work natively first.

Another option is to look how the extension [css-var-hint](https://github.com/yanai101/css-var-hint) works and try to reverse engineer the functionality of that into this, but that's something I probably won't look into.

**Comment by yeion7** [comment]
@jasonwilliams Thanks for all that info, I really appreciate it. 

I ended it building a small extension, the only thing that I couldn't figurate was how to use `typescript-styled-plugin` to read a `DocumentText`, so for know I'm just reading the file, and line by line finding variables. not the best solution but works for now

https://marketplace.visualstudio.com/items?itemName=yeion7.styled-global-variables-autocomplete
