### ISSUE TITLE
Styled-components extension not working 

### ISSUE THREAD

**Issue by kavinkumar807** [styled-components/vscode-styled-components#324]
![16312575845215203856982352363415](https://user-images.githubusercontent.com/61575461/132814008-ad510f7a-70ca-4297-bb56-de1a109cd747.jpg)

**Comment by kavinkumar807** [comment]
I've tried to reload too but it's not working

**Comment by samishoux** [comment]
If you have the same issue as me, here is what I did to fix the problem of syntax highlighting. 
If you reload your vs code and the can briefly see the highlighted color **and** the intellisense is working, the issue is because another extension is overriding the colors. For me, this extension was  [https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter](this). 
Hope this helps.
