### ISSUE TITLE
Syntax highlight is not working 

### ISSUE THREAD

**Issue by wung-s** [styled-components/vscode-styled-components#5]
Vs Code version: 1.7.2
Mac OS Seirra 10.12.1

I just installed the extension, but I do not see any change to the styled component CSS highlight. Wondering if it's specific to my system. :confused:

![screen shot 2016-11-23 at 7 42 47 am](https://cloud.githubusercontent.com/assets/5159585/20549235/885575b8-b150-11e6-9e8e-3afa0fd36e3e.png)

**Comment by julienp** [comment]
I'm sorry if I'm misunderstanding, but this looks highlighted mostly correct to me. 

If you are referring to the units being the same colour as the numbers (1.25em, 0.5em, ...), that's probably due to the theme. This looks like Dark+ theme, which seemingly doesn't apply a different colour to units.
If highlighting wasn't working, I would expect all the CSS to be the same colour.

**Comment by julienp** [comment]
Closing, feel free to re-open if I misunderstood the issue!
