### ISSUE TITLE
Emmet Autocomplete Issues

### ISSUE THREAD

**Issue by ekfuhrmann** [styled-components/vscode-styled-components#72]
I see that #56 added the ability for emmet shortcuts, however I'm having issues getting any of them to work.

Even the example of `m10` into `margin: 10px;` is not actually working.

Is there an additional setting config required to get this working?

**Comment by Cu3PO42** [comment]
This appears to work fine for me.

VSCode expands Emmet shortcuts from the auto-completion menu, so you can try to hit Ctrl+Space or Cmd+Space after the shortcut to see if an expansion is offered.

**Comment by pavsidhu** [comment]
I think @ekfuhrmann is referring to the fact that when in a .css file, when typing `m10` the tab key can be used to autocomplete to `margin: 10px;` but when inside a styled component, pressing tab does nothing, yet when opening the autocomplete suggestions menu using `cmd-space` shows the suggestion.

**Comment by francoiscote** [comment]
This seems related to an Emmet setting. Search for `Emmet` in your VS Code Settings, and check the **Trigger Expansion On Tab**. With this option on, when I type `mb10` + `Tab` inside a SC Template Literal, it completes it to `margin-bottom: 10px;`

**Comment by ekfuhrmann** [comment]
@francoiscote I can confirm that checking that box does seem to remedy it -- thanks for figuring out a solution as to why it wasn't working!

**Comment by psullivan6** [comment]
I know this issue is closed, but since it showed in my search results I wanted to add that I had to write the following VSCode configuration to make the emmet autocompletion work properly:

```
"emmet.includeLanguages": {
  "javascript": "css"
},
```

**Comment by pixelize** [comment]
@psullivan6 this seems not working in my vs code ? Any other suggestion please ? :)

![ezgif-2-0778d3a2b11d](https://user-images.githubusercontent.com/2931627/49511881-a4469880-f88c-11e8-80ae-3a5baa268bc2.gif)

**Comment by psullivan6** [comment]
@pixelize I presume you're running into an issue with VSCode trying to parse the correct context since you have JSX mixed with styled-components CSS-in-JS _(just an assumption)_. A useful pattern that I've used is to separate the styled-component declarations into a separate `styles.js` file and then import them via tree-shaking into the main component file. For example: `import { MenuButton, Kebab } from './styles.js` or similar. I presume you're leveraging the `className` prop from `styled-components` on that wrapper div, so perhaps change that to a `Wrapper` _(or similar)_ styled-component and import it directly. Granted, none of the above will explicitly solve your direct issue, but is a workflow that will help separate concerns and _may_ help with the Emmet auto-complete.

**Comment by pixelize** [comment]
@psullivan6 thank you very much for your feedback, really appreciate ! :)

**Comment by raihan004** [comment]
> "emmet.includeLanguages": {
>   "javascript": "css"
> },

How can I enable it for both  html and css?

    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
    },
    "emmet.includeLanguages": {
        "javascript": "css"
    },

thanks

**Comment by AbdallahAbis** [comment]
> "emmet.includeLanguages": {
>     "javascript": "css"
> },

I think the only way is using an array, but I'm not sure.

```
"emmet.includeLanguages": {
    "javascript": ["javascript", "css"]
},

```

**Comment by guilhermemarconi** [comment]
@AbdallahAbis tried it, but VSCode returns a warn saying that this rule expect a string instead of an array.

I wonder if it's better to use `css` instead of `javascriptreact`...

**Comment by chovole2020** [comment]
Add extension 'vscode-styled-components'
 Happy coding guys...

**Comment by guilhermemarconi** [comment]
@chovole2020 I don't know if you're aware but _**this** is_ the respository of the `vscode-styled-components` extension 😂

---

anyway, I've never tried anything different then what we discussed here. have we any updates?

**Comment by mikeytown19** [comment]
@guilhermemarconi have you tried 
```   
 "emmet.includeLanguages": {
      "jsx": "javascriptreact, css",
      "javascript": "javascriptreact, css"
    },
```
I'm having the same issue, but this seems to work sometimes for me.

**Comment by corysimmons** [comment]
I think the bigger problem might lie within the "When" condition of the keybind conflicting with the general purpose usage of `Tab`.

`config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus`
![image](https://user-images.githubusercontent.com/224636/113377762-3965d900-9343-11eb-8d00-49a2f0c10d55.png)


`editorTextFocus && !editorReadonly && !editorTabMovesFocus`
![image](https://user-images.githubusercontent.com/224636/113377878-8e095400-9343-11eb-8840-ef1d79d3adf4.png)

Specifically, although https://github.com/Microsoft/typescript-styled-plugin#configuration makes it possible to get Intellisense in template literals, the general use of `Tab` for indentation overrides Emmet.

What's interesting is that when I remove all the "When" conditions from the Emmet `Tab` keybind, it works as expected (but is really heavy handed and will expand JS when I'm simply trying to indent something).

So wisdom would suggest just changing the keybinding to something unused. But then it just doesn't expand (although using the "Emmet: Expand Abbreviation" command from the Command Palette does work).

Has... anyone ever actually expanded `m0` to `margin: 0;` inside of a styled-component template literal within VSCode? I've just gone without Emmet for years since I started developing React because abbreviation expansion just doesn't work. Kind of sad really... I loved Emmet. :(

**Comment by corysimmons** [comment]
I just figured out that if I add `"emmet.triggerExpansionOnTab": true` to my VSCode's `settings.json`, I can Emmet as expected.

I literally haven't used one of my favorite plugins for years because I just thought it was broke in VSCode or JSX/styled-components... and it was like... the very [first direction](https://code.visualstudio.com/docs/editor/emmet#_using-tab-for-emmet-expansions) in the README.

I'm going to go slam my head against the wall... 🤦

**Comment by guilhermemarconi** [comment]
@mikeytown19 just follow what @corysimmons told above and that's it, without having to change my `emmet.includeLanguages`.

```
"emmet.triggerExpansionOnTab": true,
"emmet.includeLanguages": {
  "javascript": "javascriptreact"
}
```

it just works!

**Comment by mikeytown19** [comment]
@guilhermemarconi Works for me <3 thanks!

**Comment by jasonwilliams** [comment]
Do you feel we should update the documentation so that other people can spot this? I have a feeling there may be others out there who will fall short of missing this fix.

I would appreciate if there's anyone who wants to update the readme, or even suggest in this thread what should be mentioned.

**Comment by guilhermemarconi** [comment]
@jasonwilliams actually it is already in the README, as @corysimmons told in his comment above 😊

**Comment by jasonwilliams** [comment]
Oh I meant the readme for this project

**Comment by corysimmons** [comment]
@jasonwilliams I added something here: https://github.com/styled-components/vscode-styled-components/pull/280 Feel free to word it however you want, but I think you're right that including some minimal docs here would help people sort this out faster. (I know the only place I go to for usage instructions is around the top of a README then I just assume the project is busted)

**Comment by main1479** [comment]
> ```
> "emmet.triggerExpansionOnTab": true,
> "emmet.includeLanguages": {
>   "javascript": "javascriptreact"
> }
> ```

@guilhermemarconi works for me. thanks a lot❤️

**Comment by chovole2020** [comment]
Happy coding 😁 👍

**Comment by zerihun-tesfaye** [comment]
"emmet.includeLanguages": {
  "javascript": "css"
},
