### ISSUE TITLE
Single line comments highlighting

### ISSUE THREAD

**Issue by karolisgrinkevicius** [styled-components/vscode-styled-components#74]
Hey. For some reasons it does not highlight single line comments in `tsx` files.
![screen shot 2018-03-29 at 16 00 53](https://user-images.githubusercontent.com/9420403/38090179-68606e96-336a-11e8-867d-03376fde52cd.png)

**Comment by Cu3PO42** [comment]
Right now this is intentional behaviour since I was under the impression that `styled-components` didn't support these comments as they aren't supported by CSS and neither do they appear to work on the home page.

If someone can confirm that single line comments are supported, I can add syntax highlighting for them.

**Comment by karolisgrinkevicius** [comment]
Yes, it's supported by `stylelint-processor-styled-components`. See https://github.com/styled-components/stylelint-processor-styled-components/issues/156.

**Comment by Cu3PO42** [comment]
Thanks for the confirmation. I'll try to get to that soon then.

**Comment by LAITONEN** [comment]
@Cu3PO42 any progress with this?

**Comment by quicksnap** [comment]
Also affected by this bug. Appreciate any time you have to fix it! If there's a way we could bounty a fix for this, I could surely pool a little bit of cash =)

**Comment by sigo** [comment]
Fix will be good for me also. :)

<img width="1126" alt="Screenshot 2019-07-02 at 11 41 05" src="https://user-images.githubusercontent.com/321881/60502699-9809a900-9cbe-11e9-871f-41d49dc09136.png">
