### ISSUE TITLE
Highlighting Broken after using withComponent("element")

### ISSUE THREAD

**Issue by ekfuhrmann** [styled-components/vscode-styled-components#75]
![image](https://user-images.githubusercontent.com/8878152/38096672-7671df8e-3341-11e8-8af7-30cec569e70a.png)

![image](https://user-images.githubusercontent.com/8878152/38096762-a9a47448-3341-11e8-820a-8a8c1bdf170a.png)

Specifically it seems that passing an element into the `withComponent()` function is what breaks highlighting.

**Comment by bsutt123** [comment]
So I'll take a look and see if I can find something. As a quick fix, I recommend moving the component definition below the class. Syntax highlighting normally breaks because the `/`` doesn't get captured so the whole rest of the document is a string.

I think that in this case if you use `withComponent` and `extends` then the syntax highlighting doesn't capture that case. I'll see what I can do.

**Comment by Cu3PO42** [comment]
It is indeed an issue with `withComponent` and `extend` in the same statement.

This *should* be correctly handled by the grammar. It's a weird issue with a scope not ending when it should.
