### ISSUE TITLE
Support passing type parameters to styled function

### ISSUE THREAD

**Issue by Cu3PO42** [styled-components/vscode-styled-components#81]
TypeScript 2.9 will support passing type parameters to tagged template literals, i.e.

```tsx
styled<Props>`
  color: black;
`;
```

will become valid. The plugin should support this syntax and trigger the syntax highlighting.

**Comment by alex-sherwin** [comment]
TS 2.9 is live now, so the new type parameter to tagged template literals is working great, but this plugin loses it's syntax highlighting when in use

**Comment by Cu3PO42** [comment]
Yes, this is still on the To-Do list. I currently don't have time to work on it, but pull requests would be appreciated.

**Comment by kachkaev** [comment]
I think a more likely use case is ```styled.tag<Props>`...` ``` rather than `` styled<Props>`...` ``

Example:
```tsx
const MyComponent = styled.div`
  background: yellow;
  color: red;
`;

const MyComponentWithParams = styled.div<{ something?: boolean }>`
  background: yellow;
  color: ${(p) => (p.something ? "green" : "red")};
`;
```

Current look in VSCode:

 ![screen shot 2018-08-21 at 11 28 11](https://user-images.githubusercontent.com/608862/44396613-5a33e400-a535-11e8-991c-0f43c63a149d.png)

_(the first block is highlighted and the second one is not)_

Types in template literals work for me in `next@7.0.0-canary.0` + `@zeit/next-typescript@1.1.1-canary.2` 🎉 This means that they may be widely used soon after the release of 7.0.0 😉

**Comment by ConneXNL** [comment]
any update on this?

I get the same problem as kachkaev on the second example. Type hinting works but the colors are all flat.

**Comment by CosmaTrix** [comment]
Hi all,

Any update on this issue? As you can see in the image the `Container` is higlighted correctly, while `Item<Props>` is not. 😞 

![image](https://user-images.githubusercontent.com/3206387/53546389-7dff6480-3b2c-11e9-8ed6-aa425f5da18a.png)

This is the stack I've been using
- Visual Studio Code 1.31.1
- Create React App 2.1.5
- React & ReactDOM 16.8.3
- styled-components 4.1.3
- TypeScript 3.3.3333
- typescript-styled-plugin 0.14.0
